language: node_js

dist: trusty

node_js:
  - "4"
  - "6"
  - "8"

sudo: false

branches:
  only:
    - master

addons:
  chrome: stable

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

  # Run google chrome in headless mode
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Chrome-addon-in-the-headless-mode
  # https://docs.travis-ci.com/user/chrome
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - yarn install

script:
  - yarn run check
  - yarn test
  - yarn run test-func-install
  - yarn run test-func-build
  - yarn run test-func
  # **Notes**
  # Firefox has driver issues.
  # - ROWDY_SETTINGS=local.firefox node_modules/.bin/builder run test-func-static-prod
  # Phantom has started to fail builds
  # https://github.com/FormidableLabs/victory-docs/issues/364
  # - ROWDY_SETTINGS=local.phantomjs node_modules/.bin/builder run test-func-static-prod
